# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pig}
  s.version = "0.0.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jim Remsik"]
  s.date = %q{2010-08-20}
  s.description = %q{A rack endpoint to dynamically view the latest N formatted commits.  Pig takes its name from the classic story of the chicken and the pig.  Many versions of this idea exist as jokes or anecdotes wherein the two decide to start a restaurant named Ham-n-Eggs.  Ultimately, the pig chooses not to participate because he would be committed and the chicken merely involved.}
  s.email = %q{bigtiger@hashrocket.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.textile"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".rspec",
     ".rvmrc",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.textile",
     "Rakefile",
     "VERSION",
     "lib/generators/pig/pig_generator.rb",
     "lib/pig.rb",
     "pig.gemspec",
     "spec/pig_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/bigtiger/pig}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A rack endpoint to view the latest commits in the running version.}
  s.test_files = [
    "spec/pig_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<git>, ["= 1.2.5"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<git>, ["= 1.2.5"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<git>, ["= 1.2.5"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

